### ISSUE TITLE
Local packages fail to import (Internal Server Error, on Linux)

### ISSUE THREAD

**Issue by axbweiss** [webwriter-app/webwriter#77]
## Describe the bug

Importing local packages fails. This also happens with packages that would otherwise work if imported directly from npm (such as Slides, Quiz, etc.)

One of the errors includes `500 (Internal Server Error)` for domains like https://api.webwriter.app/ww/v1/_importmaps?pkg=true&id=%40webwriter%2Fword-puzzles%400.0.1-local.local when calling `updateImportMap`.

## To reproduce
Go through the steps to import a valid local package in WebWriter. After clicking on "Import", nothing is imported. Errors can be seen in the console

## Screenshots

![2024-11-23_17-29-08_screenshot](https://github.com/user-attachments/assets/967ccd0d-763c-4994-8b57-6219fb553cd9)

## Desktop
- OS: Linux 6.11.8-200.fc40.x86_64 (64-bit) (Fedora 40)
  - Browser: Chromium (Version 130.0.6723.116 (Official Build) Fedora Project (64-bit))
  - (Desktop environment: KDE6, graphics platform: WayLand )
- WebWriter Version: v0.12.5, commit 797dbea9b5db8232675358c497b22097badb4931

**Comment by salmenf** [comment]
@axbweiss This might indicate there's no bundle to import, or the bundling failed. You need to run `npx @webwriter/build dev` in your project root, then it should work. Compared to desktop, widget code is no longer bundled by WebWriter, but by the developer, instead. With that command, you automatically rebuild the widget each time the source code changes, which is detected by WebWriter, which then reloads the widget. https://webwriter.app/docs/quickstart

See if that resolves the issue, otherwise, it's a deeper problem.

**Comment by axbweiss** [comment]
Thank you, that worked! Sorry for the confusion.
